server:
  port: 9295

spring:
  application:
    name: HYSTRIX-DASHBOARD

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  metrics:
    enabled: true
    polling-interval-ms: 500

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


